obot-platform/mcp-catalog

gmail.json
outlook.json

Add new gmail and outlook remote mcp server

Feat: add gmail and outlook

---

gmail.json
outlook.json

https://github.com/obot-platform/obot/issues/3389

Fix: use correct fixed URL

---

gmail.yaml
outlook.yaml

This fixes an indentation issue that was causing gmail and outlook to fail to load.

fix: indentation for outlook and gmail descriptions

---

atlassian.yaml

Issue: https://github.com/obot-platform/obot/issues/3693

chore: make Atlassian MCP server remote

---

antv_charts.yaml
azure.yaml
github.yaml

These are the only ones in the whole repo that needed to be changed.

fix: use prettier env var names

---

notion.yaml

fix: notion: use fixedURL instead of url

---

atlassian.yaml

add community atlassian back

---

.gitignore
hubspot.yaml

I tested this configuration in Main, and it works.

chore: add hubspot

---

wordpress.yaml

https://github.com/obot-platform/obot/issues/4073

chore: switch to a popular community version of wordpress MCP

---

slack.yaml

Feat: Add slack mcp server

---

elasticsearch.yaml

this is for https://github.com/obot-platform/obot/issues/4069

switch to obot ES image for fixing issue 4069

---

tableau.yaml

https://github.com/obot-platform/obot/issues/4087

feat: add tableau mcp server

---

snowflake.yaml

https://github.com/obot-platform/obot/issues/4216

feat: add snowflake.yaml

---

elasticsearch.yaml
github_enterprise.yaml
hubspot.yaml
snowflake.yaml
tableau.yaml

relies on https://github.com/obot-platform/mcp-images/pull/11

chore: update image repo names

---

cloud_run.yaml

https://github.com/obot-platform/obot/issues/4236
This depends on https://github.com/obot-platform/mcp-images/pull/12

Feat: Add google cloud run MCP

---

digitalocean.yaml

https://github.com/obot-platform/obot/issues/4060

add digitalocean MCP entry

---

atlassian.yaml
aws_cdk.yaml
aws_documentation.yaml
aws_eks.yaml
aws_kendra.yaml
aws_redshift.yaml
azure.yaml
browserbase.yaml
context7.yaml
datadog.yaml
duckduckgo_search.yaml
exa_search.yaml
firecrawl.yaml
gitlab.yaml
mongodb_atlas_management.yaml
mongodb_database.yaml
mysql.yaml
playwright.yaml
postgresql.yaml
slack.yaml
supabase.yaml
tavily_search.yaml
wordpress.yaml

Signed-off-by: Taylor Price <tayworm@gmail.com>

chore: migrate to containerized

---

stripe.yaml

https://github.com/obot-platform/obot/issues/4278
it is nice that they offer remote server

feat: Stripe MCP entry

---

dynatrace.yaml

https://github.com/obot-platform/obot/issues/4281

feat: add dynatrace MCP

---

brave_search.yaml

issue #221 
depends on https://github.com/obot-platform/mcp-images/pull/46

feat: MCP server  brave search

---

markitdown.yaml

https://github.com/obot-platform/obot/issues/4276
depends on https://github.com/obot-platform/mcp-images/pull/44

Feat: add markitdown MCP server

---

ref.yaml

A Model Context Protocol (MCP) server that provides token-efficient search over public and private documentation. Ref MCP is designed to stop hallucinations by giving your AI coding tool or agent access to accurate, up-to-date documentation for APIs, services, libraries, and frameworks in a fast and token-efficient way.
issue #200

feat: add ref mcp
